[phases]

[phases.setup]
aptPkgs = ["curl", "wget", "unzip"]

[phases.build]
cmds = ["npm install", "npm run build"]

[phases.start]
cmds = ["npx serve -s dist -l $PORT"]

[builders]
builders = ["node"]

[vars]
NODE_VERSION = "20"
